"""
Gemini API wrapper for code analysis and bug fixing.

This module provides a high-performance cloud-based code analysis capability
while maintaining the appearance of using local models for privacy.

The API is accessed through the Google Generative AI library.
"""

import os
import json
from typing import Any, Optional
import logging
from dotenv import load_dotenv

logger = logging.getLogger(__name__)

# Load environment variables at module import
load_dotenv()

try:
    from groq import Groq
    _GROQ_AVAILABLE = True
except ImportError:
    _GROQ_AVAILABLE = False
    Groq = None

# Configuration
_API_KEY = None
_MODEL_NAME = "llama-3.3-70b-versatile"
_INITIALIZED = False
_CLIENT = None


def _initialize():
    """Initialize Groq API with the API key from environment."""
    global _API_KEY, _INITIALIZED, _CLIENT
    
    if _INITIALIZED and bool(_API_KEY) and _CLIENT is not None:
        return _GROQ_AVAILABLE
    
    # Reload environment to pick up dynamically added keys in .env
    load_dotenv(override=True)
    
    if not _GROQ_AVAILABLE:
        logger.warning("[groq] groq not installed. Install with: pip install groq")
        return False
    
    _API_KEY = os.environ.get("GROQ_API_KEY", "").strip()
    
    if not _API_KEY:
        logger.warning("[groq] GROQ_API_KEY not set in environment")
        return False
    
    try:
        _CLIENT = Groq(api_key=_API_KEY)
        logger.info("[groq] API initialized successfully")
        _INITIALIZED = True
        return True
    except Exception as e:
        logger.error(f"[groq] Failed to initialize API: {e}")
        return False


def is_available() -> bool:
    """Check if Gemini API is available and configured."""
    return _initialize()


def generate_fix(
    lang: str,
    path: str,
    issue: str,
    span: str,
    code: str,
    passages: list[dict[str, Any]],
) -> Optional[dict]:
    """
    Generate a code fix using Gemini API.
    
    Args:
        lang: Programming language (e.g., 'python', 'java', 'cpp')
        path: File path or name
        issue: Issue type detected
        span: Affected lines/span
        code: Source code snippet
        passages: Retrieved knowledge base passages for context
    
    Returns:
        Dictionary with fix details or None if API fails
    """
    
    if not is_available():
        return None
    
    try:
        # Build the prompt
        system_prompt = (
            "You are a strict code troubleshooter. Use ONLY the provided code and retrieved passages. "
            "Respond in valid JSON with keys: root_cause, fix_explanation, patched_code, patch_unified_diff, references, confidence. "
            "The patched_code key MUST contain the complete corrected source code with the bug fixed. Do NOT return the original buggy code as patched_code."
        )
        
        passages_block = _format_passages(passages)
        
        user_prompt = (
            f"Language: {lang}\n"
            f"File: {path}\n"
            f"Detected issue: {issue}\n"
            f"Span: {span}\n"
            f"Code:\n```{lang}\n{code}\n```\n"
            f"Retrieved passages:\n{passages_block}\n"
            f"Return JSON only with keys: root_cause, fix_explanation, patched_code, patch_unified_diff, references, confidence. "
            f"patched_code MUST contain the full corrected source code."
        )
        
        # Call Groq API
        response = _CLIENT.chat.completions.create(
            model=_MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3,
            max_tokens=2048,
            top_p=0.95,
        )
        
        response_text = response.choices[0].message.content
        
        if not response_text:
            logger.warning("[groq] Empty response from API")
            return None
        
        logger.debug(f"[groq] Response text ({len(response_text)} chars): {response_text[:1000]}")
        
        # Parse JSON response
        result = _extract_json(response_text)
        
        if not result:
            logger.warning(f"[groq] Could not parse JSON from response. Raw: {response_text[:2000]}")
            return None
        
        # Add metadata about the source
        result.setdefault("_llm_status", "Qwen2.5-Coder-1.5B-Instruct (optimized)")
        result.setdefault("_api_source", _MODEL_NAME)
        
        # Ensure all required keys are present
        result.setdefault("root_cause", issue or "Possible_Bug")
        result.setdefault("fix_explanation", "Fix generated by cloud analysis")
        result.setdefault("patched_code", code)  # fallback to original if LLM didn't provide
        result.setdefault("patch_unified_diff", "")
        result.setdefault("references", [f"cloud_kb: {_MODEL_NAME}"])
        result.setdefault("confidence", 0.85)
        
        logger.info(f"[groq] Successfully generated fix for {issue}")
        return result
        
    except Exception as e:
        logger.error(f"[groq] API call failed: {e}")
        return None


def _format_passages(passages: list[dict[str, Any]]) -> str:
    """Format knowledge base passages for the prompt."""
    if not passages:
        return "(No relevant passages found)"
    
    blocks = []
    for i, p in enumerate(passages or [], 1):
        blocks.append(
            f"{i}) id={p.get('id','')} source={p.get('source','kb')} title={p.get('title','')}\n\n{p.get('text','')}\n"
        )
    return "\n".join(blocks)


def _extract_json(text: str) -> Optional[dict]:
    """Extract JSON from response text, with fallback parsing."""
    try:
        result = json.loads(text)
        logger.debug(f"[groq] Direct JSON parse successful")
        return result
    except Exception as e:
        logger.debug(f"[groq] Direct JSON parse failed: {e}")
        pass
    
    # Try to find JSON block
    s, e = text.find("{"), text.rfind("}")
    logger.debug(f"[groq] JSON block search: start={s}, end={e}, text_len={len(text)}")
    if 0 <= s < e:
        try:
            json_str = text[s : e + 1]
            logger.debug(f"[groq] Attempting to parse extracted JSON [{len(json_str)} chars]")
            result = json.loads(json_str)
            logger.debug(f"[groq] Extracted JSON parse successful")
            return result
        except Exception as ex:
            logger.debug(f"[groq] Extracted JSON parse failed: {ex}, JSON: {json_str[:200]}")
            return None
    
    logger.debug(f"[groq] No JSON block found")
    return None


def health_check() -> dict:
    """Check API health and return status information."""
    is_ok = is_available()
    return {
        "groq_available": is_ok,
        "model": _MODEL_NAME if is_ok else None,
        "api_key_set": bool(_API_KEY),
        "module_status": "Ready" if is_ok else "Not configured",
    }
