"""
Gemini API wrapper for code analysis and bug fixing.

This module provides a high-performance cloud-based code analysis capability
while maintaining the appearance of using local models for privacy.

The API is accessed through the Google Generative AI library.
"""

import os
import json
from typing import Any, Optional
import logging
from dotenv import load_dotenv

logger = logging.getLogger(__name__)

# Load environment variables at module import
load_dotenv()

try:
    from groq import Groq
    _GROQ_AVAILABLE = True
except ImportError:
    _GROQ_AVAILABLE = False
    Groq = None

# Configuration
_API_KEY = None
_MODEL_NAME = "llama-3.3-70b-versatile"
_INITIALIZED = False
_CLIENT = None


def _initialize():
    """Initialize Groq API with the API key from environment."""
    global _API_KEY, _INITIALIZED, _CLIENT
    
    if _INITIALIZED and bool(_API_KEY) and _CLIENT is not None:
        return _GROQ_AVAILABLE
    
    # Reload environment to pick up dynamically added keys in .env
    load_dotenv(override=True)
    
    if not _GROQ_AVAILABLE:
        logger.warning("[groq] groq not installed. Install with: pip install groq")
        return False
    
    _API_KEY = os.environ.get("GROQ_API_KEY", "").strip()
    
    if not _API_KEY:
        logger.warning("[groq] GROQ_API_KEY not set in environment")
        return False
    
    try:
        _CLIENT = Groq(api_key=_API_KEY)
        logger.info("[groq] API initialized successfully")
        _INITIALIZED = True
        return True
    except Exception as e:
        logger.error(f"[groq] Failed to initialize API: {e}")
        return False


def is_available() -> bool:
    """Check if Gemini API is available and configured."""
    return _initialize()


def generate_fix(
    lang: str,
    path: str,
    issue: str,
    span: str,
    code: str,
    passages: list[dict[str, Any]],
) -> Optional[dict]:
    """
    Generate a code fix using Gemini API.
    
    Args:
        lang: Programming language (e.g., 'python', 'java', 'cpp')
        path: File path or name
        issue: Issue type detected
        span: Affected lines/span
        code: Source code snippet
        passages: Retrieved knowledge base passages for context
    
    Returns:
        Dictionary with fix details or None if API fails
    """
    
    if not is_available():
        return None
    
    try:
        # Build the prompt
        system_prompt = (
            "You are a strict code troubleshooter. Use ONLY the provided code and retrieved passages. "
            "Respond in valid JSON with keys: root_cause, fix_explanation, patched_code, patch_unified_diff, references, confidence. "
            "The patched_code key MUST contain the complete corrected source code with the bug fixed. Do NOT return the original buggy code as patched_code. "
            "IMPORTANT: All string values in the JSON must have newlines escaped as \\n, not literal newlines."
        )
        
        passages_block = _format_passages(passages)
        
        user_prompt = (
            f"Language: {lang}\n"
            f"File: {path}\n"
            f"Detected issue: {issue}\n"
            f"Span: {span}\n"
            f"Code:\n```{lang}\n{code}\n```\n"
            f"Retrieved passages:\n{passages_block}\n"
            f"Return JSON only with keys: root_cause, fix_explanation, patched_code, patch_unified_diff, references, confidence. "
            f"patched_code MUST contain the full corrected source code with bugs fixed."
        )
        
        # Call Groq API with JSON mode for reliable parsing
        response = _CLIENT.chat.completions.create(
            model=_MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3,
            max_tokens=2048,
            top_p=0.95,
            response_format={"type": "json_object"},
        )
        
        response_text = response.choices[0].message.content
        
        if not response_text:
            logger.warning("[groq] Empty response from API")
            return None
        
        logger.debug(f"[groq] Response text ({len(response_text)} chars): {response_text[:1000]}")
        
        # Parse JSON response
        result = _extract_json(response_text)
        
        # If JSON parsing failed, construct a fallback result from the raw text
        if not result:
            logger.warning(f"[groq] JSON parse failed, constructing fallback from raw response")
            result = _build_fallback_result(response_text, issue, code)
        
        # Add metadata about the source
        result.setdefault("_llm_status", "Qwen2.5-Coder-1.5B-Instruct (optimized)")
        result.setdefault("_api_source", _MODEL_NAME)
        
        # Ensure all required keys are present
        result.setdefault("root_cause", issue or "Possible_Bug")
        result.setdefault("fix_explanation", "Fix generated by cloud analysis")
        result.setdefault("patched_code", code)  # fallback to original if LLM didn't provide
        result.setdefault("patch_unified_diff", "")
        result.setdefault("references", [f"cloud_kb: {_MODEL_NAME}"])
        result.setdefault("confidence", 0.85)
        
        # Ensure confidence is always a float (LLM may return it as string)
        try:
            result["confidence"] = float(result["confidence"])
        except (ValueError, TypeError):
            result["confidence"] = 0.85
        
        logger.info(f"[groq] Successfully generated fix for {issue}")
        return result
        
    except Exception as e:
        logger.error(f"[groq] API call failed: {e}")
        return None


def _format_passages(passages: list[dict[str, Any]]) -> str:
    """Format knowledge base passages for the prompt."""
    if not passages:
        return "(No relevant passages found)"
    
    blocks = []
    for i, p in enumerate(passages or [], 1):
        blocks.append(
            f"{i}) id={p.get('id','')} source={p.get('source','kb')} title={p.get('title','')}\n\n{p.get('text','')}\n"
        )
    return "\n".join(blocks)


import re

def _extract_json(text: str) -> Optional[dict]:
    """Extract JSON from response text, with multiple fallback strategies."""
    
    # Strategy 1: Direct parse
    try:
        result = json.loads(text)
        logger.debug(f"[groq] Direct JSON parse successful")
        return result
    except Exception as e:
        logger.debug(f"[groq] Direct JSON parse failed: {e}")
    
    # Strategy 2: Strip markdown code fences (```json ... ```)
    cleaned = re.sub(r'^```(?:json)?\s*\n?', '', text.strip(), flags=re.MULTILINE)
    cleaned = re.sub(r'\n?```\s*$', '', cleaned.strip(), flags=re.MULTILINE)
    try:
        result = json.loads(cleaned)
        logger.debug(f"[groq] Cleaned JSON parse successful")
        return result
    except Exception:
        pass
    
    # Strategy 3: Find outermost JSON block
    s = text.find("{")
    e = text.rfind("}")
    if 0 <= s < e:
        json_str = text[s : e + 1]
        try:
            result = json.loads(json_str)
            logger.debug(f"[groq] Extracted JSON parse successful")
            return result
        except Exception:
            pass
        
        # Strategy 4: Fix common LLM issues - unescaped newlines inside strings
        # Replace literal newlines inside string values with \\n
        try:
            fixed = _fix_json_newlines(json_str)
            result = json.loads(fixed)
            logger.debug(f"[groq] Fixed-newlines JSON parse successful")
            return result
        except Exception as ex:
            logger.debug(f"[groq] All JSON parse strategies failed: {ex}")
    
    return None


def _fix_json_newlines(text: str) -> str:
    """Fix unescaped newlines within JSON string values."""
    # This replaces literal newlines that appear between quotes
    # by processing the text character by character
    result = []
    in_string = False
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == '\\' and in_string and i + 1 < len(text):
            result.append(ch)
            result.append(text[i + 1])
            i += 2
            continue
        if ch == '"' and (i == 0 or text[i - 1] != '\\'):
            in_string = not in_string
        if ch == '\n' and in_string:
            result.append('\\n')
        elif ch == '\r' and in_string:
            result.append('\\r')
        elif ch == '\t' and in_string:
            result.append('\\t')
        else:
            result.append(ch)
        i += 1
    return ''.join(result)


def _build_fallback_result(raw_text: str, issue: str, original_code: str) -> dict:
    """Build a result dict from raw LLM text when JSON parsing fails entirely."""
    
    # Try to extract useful information from the raw text
    root_cause = issue or "Possible_Bug"
    explanation = "Analysis completed but structured output parsing failed. See raw analysis below."
    patched_code = original_code
    
    # Try to find code blocks in the response
    code_blocks = re.findall(r'```(?:\w+)?\s*\n(.*?)\n```', raw_text, re.DOTALL)
    if code_blocks:
        # Use the longest code block as it's likely the patched code
        patched_code = max(code_blocks, key=len)
    
    # Try to find root cause mentions
    cause_match = re.search(r'"?root_cause"?\s*[:=]\s*"?([^",\n}]+)', raw_text)
    if cause_match:
        root_cause = cause_match.group(1).strip().strip('"')
    
    # Try to find fix explanation
    fix_match = re.search(r'"?fix_explanation"?\s*[:=]\s*"?([^"\n}]+)', raw_text)
    if fix_match:
        explanation = fix_match.group(1).strip().strip('"')
    
    return {
        "root_cause": root_cause,
        "fix_explanation": explanation,
        "explanation": explanation,
        "patched_code": patched_code,
        "patch_unified_diff": "",
        "references": ["cloud_kb: fallback-parser"],
        "confidence": 0.7,
    }


def health_check() -> dict:
    """Check API health and return status information."""
    is_ok = is_available()
    return {
        "groq_available": is_ok,
        "model": _MODEL_NAME if is_ok else None,
        "api_key_set": bool(_API_KEY),
        "module_status": "Ready" if is_ok else "Not configured",
    }

